name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master", "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Create fake local.properties
        run: echo "SCRIPT_URL=https://script.google.com/macros/s/FAKE/exec" > local.properties

      - name: Build WebAssembly Release
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'composeApp/build/dist/wasmJs/productionExecutable'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2